_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 33
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
agent_type:
    value: SAC
batch_size:
    value: 32
checkpoint_freq:
    value: 5000
clip:
    value: 5
embedding_dim:
    value: 128
env_name:
    value: game_name
env_step_limit:
    value: 100
gamma:
    value: 0.9
hidden_dim:
    value: 128
learning_rate:
    value: 0.0001
load_checkpoint:
    value: ""
log_freq:
    value: 100
max_steps:
    value: 10000
memory_size:
    value: 100000
num_envs:
    value: 8
output_dir:
    value: output
reward_shaping:
    value: true
rnd_scale:
    value: 0.3
rom_path:
    value: z-machine-games-master/jericho-game-suite/905.z5
rs_method:
    value: potential
sample_strat:
    value: uniform
seed:
    value: 0
spm_path:
    value: unigram_8k.model
tensorboard:
    value: 0
update_freq:
    value: 1
use_aux_reward:
    value: true
wandb:
    value: 1
wandb_group:
    value: ""
wandb_project:
    value: 579_textgame
